# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Stable computation of the logarithm of a sum of values
#'
#' Numerically stable computation of
#'   \code{log(sum(exp(logV)))}
#' using SIMD instructions.
#' @param logV The input vector.
#' @param accumulators The number of accumulators used (maximum 12).
#' Typically 8 is fastest, but this may be architecture-dependent.
#' For values in the range [2,12], the difference in speed is typically
#' not large (less than 10%).
#' @examples
#' logx = runif(1e5,-10000,-9000)
#' log(sum(exp(logx)))
#' ## [1] -Inf
#' logSumExp(logx)
#' ## [1] -8995.453
#'
#' ## Example with a normalized vector
#' x = runif(1e5)
#' x = x/sum(x)
#' logSumExp::logSumExp(log(x))
#' ## [1] 0
#' @details See \url{https://github.com/1j/logSumExp}
logSumExp <- function(logV, accumulators = 8L) {
    .Call('_logSumExp_logSumExp', PACKAGE = 'logSumExp', logV, accumulators)
}

#' Stable computation of the logarithm of a sum for columns of a matrix
#'
#' Numerically stable computation of
#'   \code{apply(X,2,function(x) log(sum(exp(x))))}
#' using SIMD instructions. Note that no function \code{rowLogSumExps}
#' is provided. If this is desired, the matrix should first be transposed
#' and then can be passed into \code{colLogSumExps}.
#' @param logV The input vector.
#' @param accumulators The number of accumulators used (maximum 12).
#' Typically 5 is fastest here, but this may be architecture-dependent.
#' For values in the range [2,12], the difference in speed is typically
#' not large (less than 10%).
#' @examples
#' logx = matrix(runif(1e6,-10000,-9000),1000,1000)
#' logsum = colLogSumExps(logx)
#' @details See \url{https://github.com/1j/logSumExp}
colLogSumExps <- function(logV, accumulators = 5L) {
    .Call('_logSumExp_colLogSumExps', PACKAGE = 'logSumExp', logV, accumulators)
}

#' Stable computation of element-wise sum of two vectors in log space
#'
#' Numerically stable computation of
#'   \code{log(exp(logA)+exp(logB))}
#' using SIMD instructions. 
#' @param logA The first input vector.
#' @param logB The second input vector.
#' @examples
#' ## create two vectors of similarly small log values
#' logA = runif(1e5,-10000,-9000)
#' logB = logA + rnorm(1e5,0,1)
#'
#' ## compute sum in log space
#' logC = logAddExp(logA,logB)
#' head(cbind(logA,logB,logC))
#' ##           logA      logB      logC
#' ## [1,] -9782.350 -9781.286 -9780.990
#' ## [2,] -9279.501 -9279.381 -9278.746
#' ## [3,] -9402.641 -9402.887 -9402.064
#' ## [4,] -9927.700 -9926.675 -9926.369
#' ## [5,] -9586.167 -9586.246 -9585.513
#' ## [6,] -9602.263 -9603.234 -9601.942
#' @details See \url{https://github.com/1j/logSumExp}
logAddExp <- function(logA, logB) {
    .Call('_logSumExp_logAddExp', PACKAGE = 'logSumExp', logA, logB)
}

